width = 700
height = 700
center_button = width/2 - 125
height_button = 40
width_button = 250
menu_screen = True
help_screen = False
exit_game = False
window = None
actualQuestion = 0
lost_game = False
won_game = False